%%
%%  This template for thesis of Luoyang Institute of Science and Technology
%%
%%	@author AjiaErin <gaoajia@qq.com / icpove@gmail.com>
%%	@date 2022/01/10
%%	@version v0.1.0
%%	@address https://github.com/gaoajia/LITthesis
%%	
%%
% ---------- customise the format for class  ----------
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{LITthesis}[2022/01/10 v0.1.0]
%%
%%  The second argument is optional and provides a 
%%  description of your class which will appear in the 
%%  log and other places. The description must begin 
%%  with a date in exactly the format above and 
%%  it should be the date the package was last modified. 
%%  This can be used when including the class to check 
%%  that you have a recent enough version of it. 
%%